### ISSUE TITLE
example ping does not work

### ISSUE THREAD

**Issue by RatifiedBrownie** [SeismicCore/DiscordMarkupLanguage#4] opened 2019-11-21 13:53 UTC
when i attempt to execute the example "ping" command, it returns this error in command prompt.

```js
(node:3360) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined
    at Client.<anonymous> (C:\Users\parks\Downloads\DiscordMarkupLanguage-master\index.js:44:42)
    at Client.emit (events.js:210:5)
    at MessageCreateHandler.handle (C:\Users\parks\Downloads\DiscordMarkupLanguage-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\parks\Downloads\DiscordMarkupLanguage-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\parks\Downloads\DiscordMarkupLanguage-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\parks\Downloads\DiscordMarkupLanguage-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\parks\Downloads\DiscordMarkupLanguage-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:210:5)
    at Receiver.receiverOnMessage (C:\Users\parks\Downloads\DiscordMarkupLanguage-master\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:210:5)
(node:3360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by RevokedCookie** [comment] 2019-11-21 13:59
Issue with running commands - Line 44 index.js per: ```js
    const args = message.content.slice(Object.keys(botPrefix).length).trim().split(/ +/g)
    const command = args.shift().toLowerCase()
    if (!commands.has(command)) return
    const $$ = cheerio.load(parser.parse(`./markup/commands/${command}.dml`, client, message))
    const responseE = $$('response');
    const scripts = $$('script').get()[0].children[0].data```

**Comment by itsretr0n** [comment] 2019-11-22 14:20
Seems to be an issue with cheerier failing to find a script tag in the code. I'll update code in a few hours to not require a script tag to be inserted inside the file

**Comment by RevokedCookie** [comment] 2019-11-22 14:22
@itsretr0n When fixed, please create a separate branch for testing before pushing to master :)

**Comment by RevokedCookie** [comment] 2019-11-23 03:37
Made a small change, please try this branch: https://github.com/SeismicCore/DiscordMarkupLanguage/blob/issue-4-trial/index.js and let me know the results

**Comment by RevokedCookie** [comment] 2019-11-23 03:47
Just tested the branch above, and the issue is fixed on my end. Please test it so i can push the branch to master.

**Comment by RatifiedBrownie** [comment] 2019-11-23 04:03
Thank you. No longer receiving error after pasting the new index.js file. Seems to be fixed.

**Comment by RevokedCookie** [comment] 2019-11-23 04:04
Issue verified fixed, closing issue and pushing branch to master. Thanks for reporting this issue!

**Closed by RevokedCookie** 2019-11-23 04:04 UTC
Labels: Claimed fix, Verified Fix, bug
